services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - devcontainer.env
    ports:
      - 8000:8000
  # langfuse:
  #   image: ghcr.io/langfuse/langfuse:latest
  #   container_name: langfuse
  #   depends_on:
  #     - langfuse-db
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
  #     - NEXTAUTH_SECRET=mysecret
  #     - SALT=mysalt
  #     - NEXTAUTH_URL=http://localhost:3000
  #     - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}
  #     - NEXT_PUBLIC_SIGN_UP_DISABLED=${NEXT_PUBLIC_SIGN_UP_DISABLED:-true}
  #     - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

  # langfuse-db:
  #   image: postgres:16.1
  #   container_name: langfuse-db
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - volume-langfuse-db:/var/lib/postgresql/data

volumes:
  volume-langfuse-db:
    name: volume-langfuse-db
    driver: local
