repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/pre-commit/eslint-pre-commit-hook
    rev: v3.2.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|scss|md|mdx|yaml|yml)$

  - repo: https://github.com/davidvartanian/pre-commit-mirrors-typescript
    rev: v1.0.0
    hooks:
      - id: tsc
        args: ["--noEmit"]

  - repo: local
    hooks:
      - id: lint-staged
        name: lint-staged
        entry: npx lint-staged
        language: system
